In [1]:
from src.misc import *
from src.SPECTRUM import Spectrum
from src.FITSPECTRUM import FitSpectrum
from src.DP import DP
import matplotlib.pyplot as plt
import numpy as np
from astropy.table import Table

In [2]:
spectra_data    = fits.open('/Users/hyp0515/data/0715_Spring_BGS_ALL_trimmed.fits')
cigale_data     = fits.open('/Users/hyp0515/data/IronPhysProp_v1.2_extracted.fits')
fastspecfit     = fits.open('/Users/hyp0515/data/0715_Spring_half_BGS_BRIGHT_catalog_fastspecfit.fits')

In [3]:
DP = DP()
dps_df, _, left_2comp, right_2comp = DP.extract_fits_data('./catalogs/dp_catalog.fits')

In [4]:
# DP_SPECTRA = Spectrum(spectra_data, cigale_data, fastspecfit, load_targetID=None)

In [5]:
dps_df.columns

Index(['TARGETID', 'RA', 'DEC', 'Z', 'LOGM', 'LOGSFR', 'dv_r', 'dv_l',
       'sigma_r', 'sigma_l', 'sigma_1comp', 'p_value', 'OII3726_dp',
       'OII3729_dp', 'Hbeta_dp', 'OIII4959_dp', 'OIII5007_dp', 'NII6548_dp',
       'Halpha_dp', 'NII6583_dp', 'SII6716_dp', 'SII6731_dp', 'OII3726_rank',
       'OII3729_rank', 'Hbeta_rank', 'OIII4959_rank', 'OIII5007_rank',
       'NII6548_rank', 'Halpha_rank', 'NII6583_rank', 'SII6716_rank',
       'SII6731_rank', 'dp_count'],
      dtype='object')

In [6]:
nbcs_df, model_1comp, _, _ = DP.extract_fits_data('./catalogs/nbcs_catalog.fits')
nbcs_df.columns

Index(['TARGETID', 'RA', 'DEC', 'Z', 'LOGM', 'LOGSFR', 'dv_r', 'dv_l',
       'sigma_r', 'sigma_l', 'sigma_1comp', 'p_value'],
      dtype='object')

In [7]:
classified = fits.open('./catalogs/dps_classified.fits')
classified.info()

Filename: ./catalogs/dps_classified.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       4   ()
  1  DATA          1 BinTableHDU     77   18277R x 34C   [K, E, E, E, E, E, E, E, E, E, E, E, L, L, L, L, L, L, L, L, L, L, K, K, K, K, K, K, K, K, K, K, K, K]
  2  1COMP         1 ImageHDU         8   (7781, 18277)   float32
  3  2COMP_L       1 ImageHDU         8   (7781, 18277)   float32
  4  2COMP_R       1 ImageHDU         8   (7781, 18277)   float32

In [8]:
dps_df, _, _, _ = DP.extract_fits_data('./catalogs/dps_classified.fits')
dps_df.head()

,TARGETID,RA,DEC,Z,LOGM,LOGSFR,dv_r,dv_l,sigma_r,sigma_l,...,Hbeta_rank,OIII4959_rank,OIII5007_rank,NII6548_rank,Halpha_rank,NII6583_rank,SII6716_rank,SII6731_rank,dp_count,BPT_class
0,39627739380056564,177.019318,-1.965308,0.323187,10.452706,0.941032,53.451893,-78.319199,50.218773,30.572901,...,5,8,3,6,0,1,7,9,2,512
1,39627739380057506,177.058472,-1.984356,0.102379,10.324259,-0.880754,112.483803,-62.245144,42.930370,68.479820,...,3,9,8,2,0,1,4,6,1,512
2,39627739380058467,177.097977,-1.888290,0.123931,10.402426,1.031611,88.860611,-27.739218,29.598230,52.082478,...,6,9,8,7,0,1,2,4,3,512
3,39627739380060210,177.177948,-1.988386,0.238389,10.496312,0.039087,80.845169,-86.188843,52.286289,59.410812,...,3,9,8,4,0,1,2,5,2,512
4,39627739380061198,177.216431,-1.948593,0.103277,9.514435,0.903058,88.226196,-73.512642,38.063850,50.911797,...,2,9,8,7,0,1,4,6,5,257

In [9]:
DP.get_catalog(dps_df, './catalogs/dps_classified_catalog.fits')

In [10]:
classified_catalog = fits.open('./catalogs/dps_classified_catalog.fits')
classified_catalog.info()

Filename: ./catalogs/dps_classified_catalog.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       4   ()
  1  DATA          1 BinTableHDU     77   18277R x 34C   [K, E, E, E, E, E, E, E, E, E, E, E, L, L, L, L, L, L, L, L, L, L, K, K, K, K, K, K, K, K, K, K, K, K]

In [11]:
dp_cols = ['OII3726_dp', 'OII3729_dp',
        'Hbeta_dp',
        'OIII4959_dp', 'OIII5007_dp',
        'NII6548_dp', 'Halpha_dp', 'NII6583_dp', 
        'SII6716_dp', 'SII6731_dp']
dp_rank_cols = [f'{col[:-3]}_rank' for col in dp_cols]
classified_catalog_df = Table(classified_catalog[1].data).to_pandas()
classified_catalog_df.drop(columns=dp_cols + dp_rank_cols, inplace=True)
classified_catalog_df['delta_dv'] = classified_catalog_df['dv_r']-classified_catalog_df['dv_l']

In [12]:
classified_catalog_df.head(10)

,TARGETID,RA,DEC,Z,LOGM,LOGSFR,dv_r,dv_l,sigma_r,sigma_l,sigma_1comp,p_value,dp_count,BPT_class,delta_dv
0,39627739380056564,177.019318,-1.965308,0.323187,10.452706,0.941032,53.451893,-78.319199,50.218773,30.572901,93.781639,3.714777e-05,2,512,131.771088
1,39627739380057506,177.058472,-1.984356,0.102379,10.324259,-0.880754,112.483803,-62.245144,42.930370,68.479820,117.116127,2.684713e-03,1,512,174.728943
2,39627739380058467,177.097977,-1.888290,0.123931,10.402426,1.031611,88.860611,-27.739218,29.598230,52.082478,76.266655,1.259532e-02,3,512,116.599831
3,39627739380060210,177.177948,-1.988386,0.238389,10.496312,0.039087,80.845169,-86.188843,52.286289,59.410812,118.005127,2.266533e-06,2,512,167.034012
4,39627739380061198,177.216431,-1.948593,0.103277,9.514435,0.903058,88.226196,-73.512642,38.063850,50.911797,105.518089,1.110223e-16,5,257,161.738831
5,39627739384252917,177.358017,-1.933391,0.082934,10.019835,-1.504955,54.708546,-69.906929,29.053110,49.891163,83.371140,3.184176e-05,2,260,124.615479
6,39627739384253866,177.401154,-1.923410,0.322626,10.556721,1.160900,74.912979,-84.687080,63.850082,50.759289,114.026825,3.057432e-11,2,257,159.600067
7,39627739384254171,177.415359,-1.963895,0.242680,10.280345,0.504521,111.452072,-22.938120,4.991321,78.516968,92.210381,1.483138e-02,1,512,134.390198
8,39627739384254755,177.441299,-1.894929,0.323152,10.681046,0.655952,89.465927,-91.182854,65.778587,76.477150,131.101318,1.110223e-16,3,512,180.648773
9,39627739388446113,177.554276,-1.971866,0.083630,10.489296,0.985447,71.772476,-36.191353,34.047718,53.252762,75.641853,8.015810e-14,3,5,107.963829

In [13]:
classification_map_2comp = {
    2: 'double SF', 8: 'double COMP', 32: 'double AGN', 128: 'double LINER',
    5: 'SF+COMP', 17: 'SF+AGN', 65: 'SF+LINER',
    20: 'COMP+AGN', 68: 'COMP+LINER', 80: 'AGN+LINER',
    257: 'SF+uncertain', 260: 'COMP+uncertain', 272: 'AGN+uncertain', 320: 'LINER+uncertain',
    512: 'unclassified'
}
classified_catalog_df['BPT_class'] = classified_catalog_df['BPT_class'].map(classification_map_2comp)

In [14]:
classified_catalog_df.to_csv('./catalogs/dps_classified_catalog.csv', index=False)